In [7]:
import numpy as np



In [8]:
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return np.cos(x)
    return np.sin(x)

In [9]:
# input dataset
X = np.array([  [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])


In [10]:
# output dataset            
y = np.array([[0,1,1,0]]).T


In [11]:
import random 

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)


In [12]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,4)) -1 #hidden layers has 4 input i-e 4 nodes so our nueral network maps from 3 to 4
syn1 = 2*np.random.random((4,1)) -1 #the output layer will have the hidden layer nodes as input

for iter in range(60000):

    l0 = X

    l1 = nonlin(np.dot(l0,syn0))

    l2 = nonlin(np.dot(l1,syn1))

    l2_error = y - l2

    l2_delta = l2_error*nonlin(l2,deriv=True)

    l1_error = l2_delta.dot(syn1.T)

    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)

    syn0 += l0.T.dot(l1_delta)

print ("Output After Training at layer 1:")
print (l1)
print ("Output After Training:")
print (l2)


Output After Training at layer 1:
[[-0.04085401  0.76452295  0.33490548 -0.78769454]
 [ 0.84003199 -0.94677621  0.59126979 -0.9947561 ]
 [ 0.22731446  0.90102497 -0.33528121  0.14331496]
 [-0.72352035 -0.83670725 -0.59159135  0.64810539]]
Output After Training:
[[-0.30872593]
 [-0.1885505 ]
 [ 0.0239539 ]
 [ 0.19671612]]
