In [28]:
import numpy as np



In [29]:
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [30]:
# input dataset
X = np.array([  [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])


In [31]:
# output dataset            
y = np.array([[0,1,1,0]]).T


In [32]:
import random 

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)


In [33]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,4)) -1 #hidden layers has 4 input i-e 4 nodes so our nueral network maps from 3 to 4
syn1 = 2*np.random.random((4,1)) -1 #the output layer will have the hidden layer nodes as input

for iter in range(60000):

    l0 = X

    l1 = nonlin(np.dot(l0,syn0))

    l2 = nonlin(np.dot(l1,syn1))

    l2_error = y - l2

    l2_delta = l2_error*nonlin(l2,deriv=True)

    l1_error = l2_delta.dot(syn1.T)

    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)

    syn0 += l0.T.dot(l1_delta)

print ("Output After Training at layer 1:")
print (l1)
print ("Output After Training:")
print (l2)


Output After Training at layer 1:
[[7.26191199e-01 1.16411907e-01 9.26183940e-01 9.97110310e-01]
 [1.66762801e-01 3.92990161e-04 1.66519465e-02 8.96576847e-01]
 [9.96229372e-01 8.95211165e-01 2.23120442e-02 8.38385421e-01]
 [9.52239003e-01 2.48589483e-02 3.07990327e-05 1.15301801e-01]]
Output After Training:
[[0.00260572]
 [0.99672209]
 [0.99701711]
 [0.00386759]]
