In [1]:
import numpy as np



In [2]:
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [3]:
# input dataset
X = np.array([  [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])


In [4]:
# output dataset            
y = np.array([[0,1,1,0]]).T


In [5]:
import random 

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)


In [6]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,4)) -1 #hidden layers has 4 input i-e 4 nodes so our nueral network maps from 3 to 4
syn1 = 2*np.random.random((4,3)) -1 

for iter in range(60000):

    l0 = X

    l1 = nonlin(np.dot(l0,syn0))

    l2 = nonlin(np.dot(l1,syn1))

    l2_error = y - l2

    l2_delta = l2_error*nonlin(l2,deriv=True)

    l1_error = l2_delta.dot(syn1.T)

    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)

    syn0 += l0.T.dot(l1_delta)

print ("Output After Training at layer 1:")
print (l1)
print ("Output After Training:")
print (l2)


Output After Training at layer 1:
[[9.07263932e-01 9.61977170e-02 9.64654253e-01 9.99869308e-01]
 [1.49985061e-01 1.86169359e-04 1.25827572e-02 9.29505654e-01]
 [9.99565166e-01 9.29153816e-01 1.05049266e-02 9.59566598e-01]
 [9.76448166e-01 2.24293677e-02 4.95698752e-06 3.92942373e-02]]
Output After Training:
[[0.00255294 0.00256757 0.00255818]
 [0.9977176  0.99768446 0.99769708]
 [0.99679475 0.99679831 0.99680117]
 [0.00371969 0.00371154 0.00371196]]
